language: java

before_install:
  - .scripts/update-version.sh

after_success:
  - .scripts/add-git-tag.sh

env:
  global:
    secure: K2gkHT7ykXBB0HKLYKj0R2Ully5x0oqB4FiOgaRETgb2VTaJ4CoNVIb2eLdtze6ZfLKZowdE/l/ko/HluRqBS3qXNvEfwmDAESNvVQa7O+J6umdQUvOZb1dh5U2PGCBP2qUxFrBotxSYGM4UD8NXIxuQPMNQffebryaA6h+NaG210DlBl/zIspArJITq5OxndteZrbw3RW8cAZQOSXEs5dHb1Xg8T9FqgHtoTC5Rea75rZ8AtZ3DGG5fo0y5jUSmw9dbNg4op0cUxOZj0r2TquRx3D/EaurKQC3s2k5KgwAUtPIQLe/Zb0znKNwgN3qUZbTVeAZyHORfjbXj27mPWRAOUTGi+FdOrYB87xXvwRIsfq2mh92fUtgtzjbiyj2RBtct4wN9YmeXzFjPwZPA17SNatAX37f8luQSVOqe02t3ja/bwI2PtyS6brrcYbJQr2YBihnjmgwJiYvzL/mo1ELruwN6os9hRgHVYf1o5ojl8EbhsaX0wERbIyiPl5VnSLhE4P9VAh+v8ZzM1NpuvoAra8IHrNxG1h9TQQNaiPyL5AuBHndR8CLW7dPP+oND93Q/RaYWn8mb4QnViVYZSvp+mXKZNU3ZW5IxtCH2VH0ptg0WWb/M9/wsc8xYq0qa69oY3JwBF7KaUwUswBRG0hbYQyvPnENPHBbM0MpPNl0=
