language: java

branches:
  only:
    - master

before_install:
  - .scripts/update-version.sh

after_success:
  - .scripts/add-git-tag.sh

before_deploy:
  - .scripts/prepare-bintray.sh

env:
  global:
    secure: K2gkHT7ykXBB0HKLYKj0R2Ully5x0oqB4FiOgaRETgb2VTaJ4CoNVIb2eLdtze6ZfLKZowdE/l/ko/HluRqBS3qXNvEfwmDAESNvVQa7O+J6umdQUvOZb1dh5U2PGCBP2qUxFrBotxSYGM4UD8NXIxuQPMNQffebryaA6h+NaG210DlBl/zIspArJITq5OxndteZrbw3RW8cAZQOSXEs5dHb1Xg8T9FqgHtoTC5Rea75rZ8AtZ3DGG5fo0y5jUSmw9dbNg4op0cUxOZj0r2TquRx3D/EaurKQC3s2k5KgwAUtPIQLe/Zb0znKNwgN3qUZbTVeAZyHORfjbXj27mPWRAOUTGi+FdOrYB87xXvwRIsfq2mh92fUtgtzjbiyj2RBtct4wN9YmeXzFjPwZPA17SNatAX37f8luQSVOqe02t3ja/bwI2PtyS6brrcYbJQr2YBihnjmgwJiYvzL/mo1ELruwN6os9hRgHVYf1o5ojl8EbhsaX0wERbIyiPl5VnSLhE4P9VAh+v8ZzM1NpuvoAra8IHrNxG1h9TQQNaiPyL5AuBHndR8CLW7dPP+oND93Q/RaYWn8mb4QnViVYZSvp+mXKZNU3ZW5IxtCH2VH0ptg0WWb/M9/wsc8xYq0qa69oY3JwBF7KaUwUswBRG0hbYQyvPnENPHBbM0MpPNl0=

deploy:
  provider: bintray
  file: .scripts/bintray.json
  user: mmyslyvtsev
  key:
    secure: ilSRuzMLasAjfWXpBN7Kb1+nHLRZdUWRDgMe9pJz1FAf3cWiaJFXqlRBIDnYwc3dtWl6OE/pYgjLyQIwk0K222Nxi9Q4YgCaE5k8vRXiz95bRRKeh5PMTiLSUKjkgl5xUQ/psDTLuQ0cGAdJ2ZwBQfz6XO7mxnlF+fq1kPAClyHPwVnkg6WesT/oSwsto/lA3B2WsqQjQP2Mn5VkUtueW6CIJzbeqc8IH8Ea46IuA2FZwER0GtRp2fnUxhpDvFW7BK2BXCpFa+EYvLYmf6Mt7tjzvp2GABeLHEvuHpgp2ONLlhzRU/OQ/S9o41wW1lwd3naSoNhO/kLDfbQ9oMKi0AQ/vhElrlVgLaB/YUN9tZFp/bwWBdqreu4vG6o8LyXcydvgP/VhVYzNYF1IhZyfv0RMuFEACdOuCIf5pyrMUP0bhmtW3jpWUXB5SMs942wx631aSjrAYQhcKd53MEX3Kl1iM2DLWXK/usjye2/m9bGzWkWaAAkajvSrPwq4Z+Rh7xe0sgLLkHsZ6DrD+ZcVJ5TPP5hpB31KqaoIkVQW0A4YFer/Wj2VccuFxN7hucQmqZ90wAmBPVNSGT0HRp52xdbvjq7qrxPURHtufoHkPm0rpSBsKC8/1tmXsiV+V0lRozj28UPflqfy3e6RFNuhetH24e9srbG8YNKDr7wxnYI=
  dry-run: true
  on:
    branch: master
