language: java

branches:
  only:
    - master

before_install:
  - .scripts/update-version.sh

install: mvn install -DskipTests=true

after_success:
  - .scripts/add-git-tag.sh

before_deploy:
  - .scripts/prepare-bintray.sh

env:
  global:
    secure: mv7uZJrj8IrB3IGfaVDzSa5jeJn2QLUdsudd9GlR4pw7T1jf5zZC48nEz41oV9bR8K4fyOAZhKKhfiA38GcESUoDqWLQfmdpzn4xaVJTT32gzChvcU1Nw5dH8yZGcF2vaAnij4FZB+D4hscZnh6Ustvjg6iBEGnbG2soBnjca6hdqrXE1kBE4vV/OMz+eYDRz9HD/yNAFAXoiGMROBVMC+V/Lp17b1+hp9Rcmhu22Oi52zCFLhF7ZKxvoJnpYzqJOwm/7m/5lMBcbrGiojg1LejagsklgBcH2XLGLm3LFTxX299MTa+AjsY5Udlu23ZqSysjgGM0p77KI2z8Pm2jhW/br6EnPgDQqYgwCNF3ERPykhvNK8Ke2mrZb7X0/Bzlb2OxBUspPBSaTAAFfkONRv2TB82cqP1TO7+PvYXiRHiyQzEV3YLwVKbcBF+epo2kxYngDur3fV3w7SBa7cZkGSYtMmxhktoT4o58V25KcNVbSEGU2dnXNew+uTj9/ck941/HV/h/nvi+gpuH+oL+0NSOYi+NsIZHK7/XFuBnTwtijho+fQDRSDJoEujhgbLZ28vlQupTMd1hvorLwcAFeASemynlEM9Sd/6P0L8SyXfn5V8btTmERi1q3grGW77omfiEOCYP7eUQjEkBSgyuBOOfpLRGc4o50MMdm8Foo28=

deploy:
  provider: bintray
  file: .scripts/bintray.json
  user: mmyslyvtsev
  key:
    secure: ilSRuzMLasAjfWXpBN7Kb1+nHLRZdUWRDgMe9pJz1FAf3cWiaJFXqlRBIDnYwc3dtWl6OE/pYgjLyQIwk0K222Nxi9Q4YgCaE5k8vRXiz95bRRKeh5PMTiLSUKjkgl5xUQ/psDTLuQ0cGAdJ2ZwBQfz6XO7mxnlF+fq1kPAClyHPwVnkg6WesT/oSwsto/lA3B2WsqQjQP2Mn5VkUtueW6CIJzbeqc8IH8Ea46IuA2FZwER0GtRp2fnUxhpDvFW7BK2BXCpFa+EYvLYmf6Mt7tjzvp2GABeLHEvuHpgp2ONLlhzRU/OQ/S9o41wW1lwd3naSoNhO/kLDfbQ9oMKi0AQ/vhElrlVgLaB/YUN9tZFp/bwWBdqreu4vG6o8LyXcydvgP/VhVYzNYF1IhZyfv0RMuFEACdOuCIf5pyrMUP0bhmtW3jpWUXB5SMs942wx631aSjrAYQhcKd53MEX3Kl1iM2DLWXK/usjye2/m9bGzWkWaAAkajvSrPwq4Z+Rh7xe0sgLLkHsZ6DrD+ZcVJ5TPP5hpB31KqaoIkVQW0A4YFer/Wj2VccuFxN7hucQmqZ90wAmBPVNSGT0HRp52xdbvjq7qrxPURHtufoHkPm0rpSBsKC8/1tmXsiV+V0lRozj28UPflqfy3e6RFNuhetH24e9srbG8YNKDr7wxnYI=
  on:
    branch: master
